In [1]:
import os, sys, time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import healpy as hp

from rubin_sim.data import get_data_dir
import sqlite3

from sat_utils import Constellation, starlink_constellation_v1

In [2]:
# load up some visits

limit = 60

dd = get_data_dir()
baseline_file = os.path.join(dd,'sim_baseline/baseline.db')

# Conenct to the sqlite database
con = sqlite3.connect(baseline_file)

# Load up the first year
df = pd.read_sql('select * from observations where night < 1 limit %i;' % limit, con)

con.close()

In [3]:
# data frame with a list of observations
df

observationId     fieldRA   fieldDec  observationStartMJD  flush_by_mjd  \
0               0  310.024480 -60.812928         60218.001806  60218.023576   
1               1  310.601871 -63.561425         60218.002254  60218.023576   
2               2  311.292611 -66.317774         60218.002703  60218.023576   
3               3  312.140731 -69.082666         60218.003152  60218.023576   
4               4  304.170163 -73.375442         60218.003623  60218.023576   
5               5  304.269558 -70.565222         60218.004072  60218.023576   
6               6  310.024480 -60.812928         60218.004959  60218.023576   
7               7  310.601871 -63.561425         60218.005408  60218.023576   
8               8  311.292611 -66.317774         60218.005856  60218.023576   
9               9  312.140731 -69.082666         60218.006305  60218.023576   
10             10  304.170163 -73.375442         60218.006777  60218.023576   
11             11  304.269558 -70.565222         60218.007226  60218.023576   
12             12  304.269558 -70.565222         60218.007664  60218.051312   
13             13  312.140731 -69.082666         60218.008134  60218.051312   
14             14  311.292611 -66.317774         60218.008582  60218.051312   
15             15  310.601871 -63.561425         60218.009031  60218.051312   
16             16  316.260480 -61.800448         60218.009497  60218.051312   
17             17  310.024480 -60.812928         60218.009961  60218.051312   
18             18  315.261515 -59.086430         60218.010427  60218.051312   
19             19  309.532770 -58.069624         60218.010891  60218.051312   
20             20  314.410657 -56.370564         60218.011357  60218.051312   
21             21  309.114031 -55.322763         60218.011821  60218.051312   
22             22  313.671007 -53.641412         60218.012288  60218.051312   
23             23  308.803141 -52.531933         60218.012752  60218.051312   
24             24  309.123429 -49.431106         60218.013201  60218.051312   
25             25  313.005702 -50.837343         60218.013658  60218.051312   
26             26  317.762652 -51.736602         60218.014119  60218.051312   
27             27  320.420411 -49.108050         60218.014581  60218.051312   
28             28  324.640638 -49.244098         60218.015036  60218.051312   
29             29  322.271116 -52.014794         60218.015495  60218.051312   
30             30  326.752533 -52.083858         60218.015950  60218.051312   
31             31  318.828042 -54.459347         60218.016437  60218.051312   
32             32  323.866297 -54.791599         60218.016896  60218.051312   
33             33  319.963523 -57.140989         60218.017358  60218.051312   
34             34  321.271927 -59.809501         60218.017806  60218.051312   
35             35  325.499744 -57.483574         60218.018268  60218.051312   
36             36  330.929594 -57.500702         60218.018726  60218.051312   
37             37  327.328933 -60.125471         60218.019184  60218.051312   
38             38  333.291695 -60.093699         60218.019643  60218.051312   
39             39  329.465023 -62.728519         60218.020100  60218.051312   
40             40  322.819182 -62.468393         60218.020563  60218.051312   
41             41  317.457268 -64.514817         60218.021027  60218.051312   
42             42  324.687289 -65.114962         60218.021493  60218.051312   
43             43  332.026123 -65.290857         60218.021958  60218.051312   
44             44  326.991724 -67.741884         60218.022418  60218.051312   
45             45  318.924263 -67.228227         60218.022886  60218.051312   
46             46  320.772323 -69.936395         60218.023335  60218.051312   
47             47  329.905837 -70.336228         60218.023806  60218.051312   
48             48  333.694145 -72.875822         60218.024255  60218.051312   
49             49  323.178355 -72.630625         60218

In [4]:
# Make a satellite constellation
tles = starlink_constellation_v1()
constellation = Constellation(tles)

In [5]:
# Check the first method
lengths = []
nstreaks = []
n_rows = len(df)
t1 = time.time()
for index, row in df.iterrows():
    length, streak = constellation.check_pointing(row['altitude'], row['azimuth'],
                                    row['observationStartMJD'], row['visitTime'])
    lengths.append(length)
    nstreaks.append(streak)
    # A simple progress bar
    progress = index/float(n_rows)*100
    text = "\rprogress = %.3f%%" % progress
    sys.stdout.write(text) 
    sys.stdout.flush() 
t2 = time.time()
print('runtime = %.2f min' % ((t2-t1)/60.) )

progress = 98.333%runtime = 11.13 min


In [16]:
# check the new method
t1 = time.time()

fast_lengths, fast_nstreaks = constellation.check_pointings(df['fieldRA'].values, df['fieldDec'].values,
                                                           df['observationStartMJD'].values,
                                                           df['visitTime'].values)
t2 = time.time()
print('runtime = %.2f min' % ((t2-t1)/60.) )


runtime = 0.19 min


In [17]:
np.array(lengths)

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 3.45790382, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 3.35728576, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [18]:
fast_lengths

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 3.46212246, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 3.4627139 , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.99496856, 0.        , 0.        , 0.        ,
       2.89858297, 0.        , 0.        , 0.        , 0.        ])

In [19]:
# The good news, we got a factor of 20 speedup! The bad news, the results are supposed to match don't match.
fast_lengths[55]

2.8985829706361863

In [20]:
i=55
fast_lengths, fast_nstreaks = constellation.check_pointings(df['fieldRA'].values[i], df['fieldDec'].values[i],
                                                           df['observationStartMJD'].values[i],
                                                           df['visitTime'].values[i])

In [21]:
fast_lengths, fast_nstreaks

(array([2.89858297]), array([1]))

In [22]:
constellation.check_pointing(df['altitude'].values[i], df['azimuth'].values[i], df['observationStartMJD'].values[i],
                                                           df['visitTime'].values[i])

(0.0, 0)

In [ ]:
# So, why is the fast method finding more streaks than the slow method?